services:
  next-app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules   # ← 匿名ではなく名前付きに
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200
      - TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nextjs-prisma-graphql-codegen-dev
    restart: unless-stopped

volumes:
  mysql:
  node_modules_cache: {}
