services:
  next-app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200
      - TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=nextjs-prisma-graphql-codegen-dev
    restart: unless-stopped

volumes:
  pgdata:
  node_modules_cache: {}